version: "3"
services:
  app:
    container_name: "gpt-j-6b"
    build:
      context: .
      dockerfile: ./Dockerfile
    image: gpt-j-6b-container
    volumes:
        - ./example:/home/docker-gpt-j-6b-example
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    tty: true